database = [	#Trivandrum
		{ 'productname' : 'Poco M2', 'city' : 'Trivandrum', 'category' : 'Mobile', 'pricing' : 'Cheap' },
		{ 'productname' : 'Motorola Edge 20', 'city' : 'Trivandrum', 'category' : 'Mobile', 'pricing' : 'Average' },
		{ 'productname' : 'Apple Iphone', 'city' : 'Trivandrum', 'category' : 'Mobile', 'pricing' : 'Expensive' },
		{ 'productname' : 'Roadster', 'city' : 'Trivandrum', 'category' : 'Fashion', 'pricing' : 'Average' },
		{ 'productname' : 'Dolo', 'city' : 'Trivandrum', 'category' : 'Fashion', 'pricing' : 'Cheap' },
		{ 'productname' : 'Cashew Nut', 'city' : 'Trivandrum', 'category' : 'Grocery', 'pricing' : 'Expensive' },
		{ 'productname' : 'Headphones', 'city' : 'Trivandrum', 'category' : 'Electronics', 'pricing' : 'Average' },
		{ 'productname' : 'Laptop', 'city' : 'Trivandrum', 'category' : 'Electronics', 'pricing' : 'Expensive' },
		#Kochi
		{ 'productname' : 'Cricket Bat', 'city' : 'Kochi', 'category' : 'Sports', 'pricing' : 'Average' },
		{ 'productname' : 'Suitcase', 'city' : 'Kochi', 'category' : 'Fashion', 'pricing' : 'Average' },
		{ 'productname' : 'Samsung Note ', 'city' : 'Kochi', 'category' : 'Mobile', 'pricing' : 'Expensive' },
		{ 'productname' : 'Horlicks', 'city' : 'Kochi', 'category' : 'Grocery', 'pricing' : 'Cheap' },
		{ 'productname' : 'Football', 'city' : 'Kochi', 'category' : 'Sports', 'pricing' : 'Cheap' },
		{ 'productname' : 'Gym workout Kit', 'city' : 'Kochi', 'category' : 'Sports', 'pricing' : 'Expensive' },
		{ 'productname' : '4K TV', 'city' : 'Kochi', 'category' : 'Electronics', 'pricing' : 'Expensive' },
		{ 'productname' : 'Earphones', 'city' : 'Kochi', 'category' : 'Electronics', 'pricing' : 'Cheap' },
		#Bangalore
		{ 'productname' : 'Redmi Note 9', 'city' : 'Bangalore', 'category' : 'Mobile', 'pricing' : 'Cheap' },
		{ 'productname' : 'Samsung M51', 'city' : 'Bangalore', 'category' : 'Mobile', 'pricing' : 'Average' },
		{ 'productname' : 'Sunflower Oil', 'city' : 'Bangalore', 'category' : 'Grocery', 'pricing' : 'Average' },
		{ 'productname' : 'Football', 'city' : 'Bangalore', 'category' : 'Sports', 'pricing' : 'Average' },
		{ 'productname' : 'Yonex raquet', 'city' : 'Bangalore', 'category' : 'Sports', 'pricing' : 'Expensive' },
		{ 'productname' : 'Travel bags', 'city' : 'Bangalore', 'category' : 'Fashion', 'pricing' : 'Average' },
		{ 'productname' : 'Tshirt', 'city' : 'Bangalore', 'category' : 'Fashion', 'pricing' : 'Cheap' },
		{ 'productname' : 'Realme PowerBank', 'city' : 'Bangalore', 'category' : 'Electronics', 'pricing' : 'Average' },
		{ 'productname' : 'DSLR Camera', 'city' : 'Bangalore', 'category' : 'Electronics', 'pricing' : 'Expensive' },
		#Chennai
		{ 'productname' : 'Realme Narzo 5G', 'city' : 'Chennai', 'category' : 'Mobile', 'pricing' : 'Average' },
		{ 'productname' : 'Ashirvad Atta', 'city' : 'Chennai', 'category' : 'Grocery', 'pricing' : 'Cheap' },
		{ 'productname' : 'Peanut Butter', 'city' : 'Chennai', 'category' : 'Grocery', 'pricing' : 'Average' },
		{ 'productname' : 'Roasted Almond', 'city' : 'Chennai', 'category' : 'Grocery', 'pricing' : 'Expensive' },
		{ 'productname' : 'Bata Footwear', 'city' : 'Chennai', 'category' : 'Fashion', 'pricing' : 'Average' },
		{ 'productname' : 'Carromboard', 'city' : 'Chennai', 'category' : 'Sports', 'pricing' : 'Average' },
		{ 'productname' : 'Mobile Case', 'city' : 'Chennai', 'category' : 'Electronics', 'pricing' : 'Cheap' },
		{ 'productname' : 'DTH', 'city' : 'Chennai', 'category' : 'Electronics', 'pricing' : 'Average' },
		{ 'productname' : 'eGPU', 'city' : 'Chennai', 'category' : 'Electronics', 'pricing' : 'Expensive' }]
